import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Loader } from 'lucide-react';
import api from '../../lib/api';
import { ACCESS_TOKEN, REFRESH_TOKEN } from '../../lib/constants';
import { useAuth } from '../../context/AuthContext';

export const Login = ({ initialMode = 'signin' }) => {
  const [mode, setMode] = useState(initialMode);
  const [username, setUsername] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState('teacher');
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const navigate = useNavigate(); const location = useLocation(); const { login } = useAuth();
  const destination = location.state?.from || '/';
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { let result; let user; if (mode === 'signup') { result = await api.post('/api/auth/register/', { username: username.trim() || email.trim(), email: email.trim(), password, role }); user = result.data.user; } else { result = await api.post('/api/token/', { username: username.trim(), password }); user = (await api.get('/api/users/me/', { headers: { Authorization: `Bearer ${result.data.access}` } })).data; } localStorage.setItem(ACCESS_TOKEN, result.data.access); localStorage.setItem(REFRESH_TOKEN, result.data.refresh); api.defaults.headers.common.Authorization = `Bearer ${result.data.access}`; await login(user); navigate(destination, { replace: true }); } catch (requestError) { const detail = requestError.response?.data?.detail; setError(Array.isArray(detail) ? detail.join(' ') : detail || 'Unable to continue. Check your details and try again.'); } finally { setLoading(false); } };
  return <main className="grid min-h-screen place-items-center bg-slate-50 p-5"><section className="w-full max-w-md rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><Link to="/" className="text-sm font-semibold text-indigo-700">Alcheris</Link><h1 className="mt-6 text-2xl font-bold">{mode === 'signup' ? 'Create account' : 'Sign in'}</h1><p className="mt-2 text-sm text-slate-600">{mode === 'signup' ? 'Choose a role to build lessons or learn through them.' : 'Continue to your Alcheris workspace.'}</p><form className="mt-6 space-y-4" onSubmit={submit}>{mode === 'signup' && <><label className="block text-sm font-medium">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><div className="grid grid-cols-2 gap-2">{['teacher','student'].map((value) => <button key={value} type="button" onClick={() => setRole(value)} className={`rounded-md border px-3 py-2 text-sm capitalize ${role === value ? 'border-indigo-600 bg-indigo-50 text-indigo-700' : 'border-slate-300'}`}>{value}</button>)}</div></>}<label className="block text-sm font-medium">Username or email<input required value={username} onChange={(event) => setUsername(event.target.value)} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Password<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label>{error && <p className="text-sm text-rose-700">{error}</p>}<button disabled={loading} className="flex min-h-11 w-full items-center justify-center rounded-md bg-indigo-600 px-3 text-sm font-medium text-white disabled:opacity-60">{loading && <Loader size={15} className="mr-2 animate-spin" />}{mode === 'signup' ? 'Create account' : 'Sign in'}</button></form><p className="mt-5 text-center text-sm text-slate-600">{mode === 'signup' ? 'Already have an account?' : 'New to Alcheris?'} <button onClick={() => { setMode(mode === 'signup' ? 'signin' : 'signup'); setError(''); }} className="font-medium text-indigo-700">{mode === 'signup' ? 'Sign in' : 'Create one'}</button></p></section></main>;
};
